name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  code_coverage_linting_and_formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
        override: true

    - name: run linting (dead with warnings)
      run: cargo clippy -- -D warnings

    - name: run formatting
      run: cargo fmt -- --check
    
    - name: install tarpaulin (code coverage tool)
      run: cargo install cargo-tarpaulin
    
    - name: run coverage (finally)
      # no prebuilt tar binary???
      #uses: actions-rs/tarpaulin@v0.1.0
      run: cargo tarpaulin

  vulnerability_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: install audit
      run: cargo install cargo-audit

    - name: run audit check
      run: cargo audit
